### ISSUE TITLE
Error in completing the function in R Studio

### ISSUE THREAD

**Issue by ekleins** [iobis/obistools#18]
Just writing the function in the RStudio console and after the underscore (autocompletion is trying to guess the command) a small window appears with the message "R code Execution Error". None of the functions of the obistools are working after a fresh install

**Comment by pieterprovoost** [comment]
@ekleins Are you on Ubuntu? Which versions of R and RStudio? Can you perhaps check of the problem occurs when using the default R app or the console?

Thanks.

**Comment by ekleins** [comment]
Reboot and now is working OK. It was probably something with my system. KUbuntu 16.04.1 LTS RStudio Version 1.0.136, R version 3.3.2 (2016-10-31).
