### ISSUE TITLE
dataset tree only event core and occurrence extension

### ISSUE THREAD

**Issue by wardappeltans** [iobis/obistools#31]
enable building dataset tree when no (e)MoF is available. e.g. http://ipt.ala.org.au/archive.do?r=global

**Comment by pieterprovoost** [comment]
Fixed, please reinstall.

![screen shot 2017-09-22 at 14 43 09](https://user-images.githubusercontent.com/490041/30745174-7077ae36-9fa5-11e7-99c7-1e5e7f932c82.png)
