### ISSUE TITLE
check_depth: add option to provide additional bathymetry layers

### ISSUE THREAD

**Issue by samuelbosch** [iobis/obistools#44]

**Comment by jdpye** [comment]
Thanks, Samuel!

**Comment by samuelbosch** [comment]
I've added a bathymetry parameter. If you know of any high resolution gridded bathymetry data (better than GEBCO), that we can freely use, then let me know and I'll add them to the web service.

**Comment by jdpye** [comment]
Super cool. I'll play with this over Xmas with some localized bathymetry grids.
