### ISSUE TITLE
remove or change dependency to iobis/worms

### ISSUE THREAD

**Issue by samuelbosch** [iobis/obistools#52]
Issues:
- people that already have the CRAN worms package get installation problems when installing obistools
- iobis/worms appears to be redundant as there are other packages with similar functionality (taxize, worrms, worms)
- iobis/worms will have to be put on CRAN in order to get obistools on CRAN

I would prefer to try to replace the dependency and use another package instead (= less code for us to maintain). Alternative would be to rename iobis/worms and put it on CRAN.

**Comment by pieterprovoost** [comment]
Needs to be replaced by `worrms`.
