### ISSUE TITLE
Question regarding the source for the grid package

### ISSUE THREAD

**Issue by ocefpaf** [iobis/obistools#60]
@samuelbosch I'm wondering if the `grid` package in the [dependency list](https://github.com/iobis/obistools/blob/master/DESCRIPTION#L35) is this one:

https://cran.r-project.org/web/packages/grid/index.html

I'm asking b/c we are packaging `obistools` for conda and we are [still missing](https://github.com/conda-forge/r-obistools-feedstock/blob/master/recipe/meta.yaml#L40) that dependency.

**Comment by samuelbosch** [comment]
Yes, it's that R package, but the function where it's been used in is already giving issues so I'll remove the dependency and deprecate the function.

**Comment by ocefpaf** [comment]
Thanks for the quick response. We (conda-forge) are still missing `tmap` b/c of a dependency on `v8` somewhere. Hopefully we'll get that resolved soon and installing `obistools` with conda will be easy.
