### ISSUE TITLE
Failed to connect to api.iobis.org port 80: Connection refused   

### ISSUE THREAD

**Issue by rubenpp7** [iobis/obistools#71]
Hi all, 

I am trying to use the LifeWatch and EMODnet Biology QC tool (http://rshiny.lifewatch.be/BioCheck/) that uses functions from obistools and it give me the following Warning:

"Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused"

This issue stops the tool and does not load the datasets' IPTs

The whole message of the tool is this one (in case it can help to figure out the issue):

****************************************************************************************************
****************************************************************************************************

Loading required package: shiny
Skipping install of 'EMODnetBiocheck' from a github remote, the SHA1 (d8f5d305) has not changed since last install.
  Use `force = TRUE` to force installation

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Attaching package: ‘DT’

The following objects are masked from ‘package:shiny’:

    dataTableOutput, renderDataTable

Loading required package: EMODnetBiocheck
Loading required package: bitops
data.table 1.12.2 using 4 threads (see ?getDTthreads).  Latest news: r-datatable.com

Attaching package: ‘data.table’

The following objects are masked from ‘package:dplyr’:

    between, first, last

Loading required package: obistools

Listening on http://127.0.0.1:7233
Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused
  133: curl::curl_fetch_memory
  132: request_fetch.write_memory
  130: request_perform
  129: httr::POST
  125: service_call
  124: lookup_xy_chunk
  123: FUN
  122: lapply
  121: lookup_xy
  120: check_onland
  117: checkdataset
  114: checkIPTdataset
  113: <reactive:CheckDataset> [C:\Users\rubenp\Downloads/app.R#182]
   97: CheckDataset
   96: renderTable [C:\Users\rubenp\Downloads/app.R#227]
   95: func
   82: origRenderFunc
   81: output$mofsummary
    1: shiny::runApp
Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused
  99: <Anonymous>
Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused
  99: <Anonymous>
Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused
  99: <Anonymous>
Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused
  170: <Anonymous>
Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused
  99: <Anonymous>
Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused
  99: <Anonymous>
Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused
  138: <Anonymous>
Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused
  99: <Anonymous>
Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused
  98: <Anonymous>
Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused
  99: <Anonymous>
Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused
  99: <Anonymous>
Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused
  99: <Anonymous>
Warning: Error in curl::curl_fetch_memory: Failed to connect to api.iobis.org port 80: Connection refused
  99: <Anonymous>

**Comment by pieterprovoost** [comment]
Thanks, we are aware if the issue and fixing asap.

**Comment by pieterprovoost** [comment]
@rubenpp7 Can you please try again?

I will fix obistools so it no longer uses the deprecated api.iobis.org URL and report back here. At that point it would be good if you could update obistools on your server.

**Comment by rubenpp7** [comment]
It works now!! Thank you very much

**Comment by pieterprovoost** [comment]
The API URLs have been fixed, please update to version 0.0.9 using devtools or from https://github.com/iobis/obistools/releases/tag/v0.0.9
